### ISSUE TITLE
Plugin is not compatible with the latest Gradle version (2.7)

### ISSUE THREAD

**Issue by dabolichin** [RobWin/jgitflow-gradle-plugin#8]
When running startRelease task with gradle 2.7 following exception is thrown:
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/mvn3/org/apache/maven/artifact/ArtifactUtils
        at io.github.robwin.jgitflow.tasks.ReleaseStartTask.validateReleaseVersion(ReleaseStartTask.groovy:74)
        at io.github.robwin.jgitflow.tasks.ReleaseStartTask.start(ReleaseStartTask.groovy:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
```

When switching to gradle 2.4 everything works fine.

**Comment by RobWin** [comment]
Thx. I have a look at it. What about Gradle 2.6?

**Comment by dabolichin** [comment]
Same exception with 2.6

**Comment by RobWin** [comment]
It seems that Gradle has dropped the built-in Maven libs.

**Comment by RobWin** [comment]
Could you please test v0.3.0. It should work with Gradle 2.7 now.

**Comment by dabolichin** [comment]
Similar exception is thrown now:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/artifact/ArtifactUtils
        at io.github.robwin.jgitflow.tasks.ReleaseStartTask.validateReleaseVersion(ReleaseStartTask.groovy:74)
        at io.github.robwin.jgitflow.tasks.ReleaseStartTask.start(ReleaseStartTask.groovy:39)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by RobWin** [comment]
Very strange. The TravisCI Build is successful and it works on my environment :(

**Comment by dabolichin** [comment]
Adding `classpath gradleApi()` to dependencies solves the issue:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath gradleApi()
        classpath 'io.github.robwin:jgitflow-gradle-plugin:0.3.0'
    }
}
```

For reference see [this](https://discuss.gradle.org/t/gradle-doesnt-add-the-same-dependencies-to-classpath-when-applying-plugins/9759).

I guess you need to add it to documentation.

**Comment by RobWin** [comment]
Very good hint. thx. I have a look at it. Seems that I have to add a Maven compile dependency or the better solution would be to remove it.

**Comment by RobWin** [comment]
In v0.3.1 i have removed the maven dependency completely. The `gradleApi()´ should not be necessary anymore.
